--- #YAML:1.0
name:                Tk-DiffText
version:             0.18
abstract:            Perl/Tk composite widget for colorized diffs.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
    Algorithm::Diff:               1.13
    IO::File:                      0
    Tie::Tk::Text:                 0.01
    Tk:                            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Michael J. Carman <mjcarman@mchsi.com>
